using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InternIntellegence_MovieApi.Models{
    public class Genre{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // should not be autogenerated because i get the id from TMDB
        public int Id { get; set; }
        
        [Required]
        public string name { get; set; } = null!;
    }
}